# Site settings
name: momohan.github.io
email: hanhuilo_ve@163.com
author: momohan
url: https://momohan.github.io/
resume_site: https://momohan.github.io/
github: https://github.com/momohan/
baseurl: ""
description: momohan的个人博客!
meta_description: momohan的个人博客!
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: momohan
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

#FB:
 # comments :
 #   provider : duoshuo
  #  duoshuo:
  #      short_name : luoyan35714
  #  disqus :
   #     short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light